language: python

python:
  - 2.7

env:
  - TRAVIS_NODE_VERSION="5"

before_script:
  - npm install -g npm
  - npm install -g gulp

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - pip install cookiecutter
  - cookiecutter . --no-input
  - cd angular2-seed
  - npm install

script:
  - npm test

sudo: false
